version: '2'
services:
  mongo:
    container_name: mongo-cargo-production
    image: mongo
    ports: ["27024:27017"]
    restart: "always"
    volumes:
      - cargo-mongo-production:/data/db
  cargo:
    container_name: cargo-server-production
    image: hicsail/cargo:main
    restart: always
    depends_on:
      - mongo
      - minio
    ports: ["3006:3000"]
    env_file:
      - ../../../stack.env
  minio:
    container_name: minio-cargo-production
    image: minio/minio:RELEASE.2023-04-07T05-28-58Z.fips
    restart: "always"
    ports: ["9002:9000", "9003:9001"]
    volumes:
      - minio-production:/data
    command: server /data --console-address ":9001"
    env_file:
    - ../../../stack.env
volumes:
  cargo-production:
    external: true
  minio-production:
    external: true
