name: cargo-client
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/client/**'
    branches:
      - main
    pull_request:
      paths:
        - 'packages/client-admin/**'
      branches:
        - main

jobs:
  lint:

  build:
