name: cargo-client
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/client/**'
    branches:
      - main
  pull_request:
    paths:
      - 'packages/client/**'
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Checking Lint and Prettier
    defaults:
      run:
        working-directory: packages/client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove Top Level package.json
        run: rm ../../package.json

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: NPM Install
        run: npm install --only-dev
        shell: bash

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier

  build:
    runs-on: ubuntu-latest
    name: Build Code
    defaults:
      run:
        working-directory: packages/client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Remove Top Level package.json
        run: rm ../../package.json

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: NPM Install
        run: npm install --only-dev
        shell: bash

      - name: Build
        run: npm run build
