name: cargo-middleware
on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/middleware/**'
    branches:
      - main
  pull_request:
    paths:
      - 'packages/middleware/**'
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Checking Lint and Prettier
    defaults:
      run:
        working-directory: packages/middleware
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install
        shell: bash

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier

  build:
    runs-on: ubuntu-latest
    name: Build Code
    defaults:
      run:
        working-directory: packages/middleware
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM Install
        run: npm install
        shell: bash

      - name: Build
        run: npm run build

  publish:
    needs: [lint, build]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: NPM Publish
    defaults:
      run:
        working-directory: packages/middleware
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: npm run build

      - name: Setup NPM CI
        run: npm ci

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

